INFO 09-01 01:12:17 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
INFO 09-01 01:14:11 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 01:15:22 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'enable_prompt_embeds': True, 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 01:15:29 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 01:15:29 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 01:15:29 [__init__.py:1750] Using max model len 32768
WARNING 09-01 01:15:29 [arg_utils.py:1770] --enable-prompt-embeds is not supported by the V1 Engine. Falling back to V0. 
WARNING 09-01 01:15:30 [cuda.py:103] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 09-01 01:15:30 [__init__.py:3565] Cudagraph is disabled under eager mode
INFO 09-01 01:15:30 [llm_engine.py:222] Initializing a V0 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{"enable_fusion":false,"enable_noop":false},"max_capture_size":0,"local_cache_dir":null}, use_cached_outputs=False, 
INFO 09-01 01:15:32 [cuda.py:436] Using Flash Attention backend.
INFO 09-01 01:15:32 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 09-01 01:15:32 [model_runner.py:1080] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-01 01:15:33 [weight_utils.py:296] Using model weights format ['*.safetensors']
INFO 09-01 01:15:51 [weight_utils.py:312] Time spent downloading weights for Qwen/Qwen2.5-7B-Instruct: 18.277447 seconds
INFO 09-01 01:15:55 [default_loader.py:262] Loading weights took 3.94 seconds
INFO 09-01 01:15:55 [model_runner.py:1112] Model loading took 14.2488 GiB and 22.495264 seconds
INFO 09-01 01:16:00 [worker.py:295] Memory profiling takes 4.41 seconds
INFO 09-01 01:16:00 [worker.py:295] the current vLLM instance can use total_gpu_memory (47.53GiB) x gpu_memory_utilization (0.80) = 38.02GiB
INFO 09-01 01:16:00 [worker.py:295] model weights take 14.25GiB; non_torch_memory takes 0.00GiB; PyTorch activation peak memory takes 4.34GiB; the rest of the memory reserved for KV Cache is 19.43GiB.
INFO 09-01 01:16:00 [executor_base.py:114] # cuda blocks: 22738, # CPU blocks: 4681
INFO 09-01 01:16:00 [executor_base.py:119] Maximum concurrency for 32768 tokens per request: 11.10x
INFO 09-01 01:16:02 [llm_engine.py:417] init engine (profile, create kv cache, warmup model) took 7.12 seconds
INFO 09-01 01:16:03 [llm.py:298] Supported_tasks: ['generate']
INFO 09-01 01:19:46 [__init__.py:241] Automatically detected platform cuda.
INFO 09-01 01:20:09 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 01:21:21 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'enable_prompt_embeds': True, 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 01:21:30 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 01:21:30 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 01:21:30 [__init__.py:1750] Using max model len 32768
WARNING 09-01 01:21:30 [arg_utils.py:1770] --enable-prompt-embeds is not supported by the V1 Engine. Falling back to V0. 
WARNING 09-01 01:21:30 [cuda.py:103] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 09-01 01:21:30 [__init__.py:3565] Cudagraph is disabled under eager mode
INFO 09-01 01:21:30 [llm_engine.py:222] Initializing a V0 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{"enable_fusion":false,"enable_noop":false},"max_capture_size":0,"local_cache_dir":null}, use_cached_outputs=False, 
INFO 09-01 01:21:32 [cuda.py:436] Using Flash Attention backend.
INFO 09-01 01:21:33 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 09-01 01:21:33 [model_runner.py:1080] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-01 01:21:33 [weight_utils.py:296] Using model weights format ['*.safetensors']
INFO 09-01 01:21:38 [default_loader.py:262] Loading weights took 4.65 seconds
INFO 09-01 01:21:38 [model_runner.py:1112] Model loading took 14.2488 GiB and 4.965910 seconds
INFO 09-01 01:21:43 [worker.py:295] Memory profiling takes 4.34 seconds
INFO 09-01 01:21:43 [worker.py:295] the current vLLM instance can use total_gpu_memory (47.53GiB) x gpu_memory_utilization (0.80) = 38.02GiB
INFO 09-01 01:21:43 [worker.py:295] model weights take 14.25GiB; non_torch_memory takes 0.00GiB; PyTorch activation peak memory takes 4.34GiB; the rest of the memory reserved for KV Cache is 19.43GiB.
INFO 09-01 01:21:43 [executor_base.py:114] # cuda blocks: 22738, # CPU blocks: 4681
INFO 09-01 01:21:43 [executor_base.py:119] Maximum concurrency for 32768 tokens per request: 11.10x
INFO 09-01 01:21:45 [llm_engine.py:417] init engine (profile, create kv cache, warmup model) took 7.01 seconds
INFO 09-01 01:21:46 [llm.py:298] Supported_tasks: ['generate']
INFO 09-01 01:22:14 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
INFO 09-01 01:31:04 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 01:32:18 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.8, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 01:32:27 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 01:32:27 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 01:32:27 [__init__.py:1750] Using max model len 32768
INFO 09-01 01:32:27 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 01:32:27 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 01:32:28 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 01:32:33 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1071447)[0;0m INFO 09-01 01:32:36 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1071447)[0;0m INFO 09-01 01:32:36 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1071447)[0;0m ERROR 09-01 01:32:38 [core.py:700] ValueError: Free memory on device (32.05/47.53 GiB) on startup is less than desired GPU memory utilization (0.8, 38.02 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 01:34:23 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 01:35:36 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 01:35:43 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 01:35:43 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 01:35:43 [__init__.py:1750] Using max model len 32768
INFO 09-01 01:35:44 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 01:35:44 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 01:35:44 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 01:35:50 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1092519)[0;0m INFO 09-01 01:35:52 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1092519)[0;0m INFO 09-01 01:35:52 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1092519)[0;0m ERROR 09-01 01:35:54 [core.py:700] ValueError: Free memory on device (32.05/47.53 GiB) on startup is less than desired GPU memory utilization (0.92, 43.73 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 01:37:31 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
INFO 09-01 01:52:31 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
INFO 09-01 02:01:23 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 02:02:20 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 02:02:26 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 02:02:26 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 02:02:26 [__init__.py:1750] Using max model len 32768
INFO 09-01 02:02:27 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 02:02:27 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 02:02:28 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 02:02:33 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1110674)[0;0m INFO 09-01 02:02:36 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1110674)[0;0m INFO 09-01 02:02:36 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1110674)[0;0m ERROR 09-01 02:02:38 [core.py:700] ValueError: Free memory on device (32.05/47.53 GiB) on startup is less than desired GPU memory utilization (0.92, 43.73 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 02:05:50 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image is a collage of various photos featuring a woman's face. There are multiple instances of t...
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5c.png
[WARN] Path not found: download/output/figures/2310.07894v1/tex_figures_5d.png
[WARN] Path not found: download/output/figures/1806.05594v3/figs_exps_results_epochs_c10_cnn_MT_4k_wmodelTrue_nolegend
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_demog
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_time
[WARN] Path not found: download/output/figures/2508.00717/results_ai_use_model
[WARN] Path not found: download/output/figures/2508.00717/results_ai_pays_dem
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image features a black background with a pattern of dots, which are scattered across the entire ...
LLaVA description: The image is a black and white graphic featuring a pattern of dots, with each dot having a different...
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines and columns, likely representing data or information....
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image displays a graph with multiple lines, each representing a different data set. The lines ar...
LLaVA description: The image is a collection of graphs and charts, each displaying different types of data. There are a...
LLaVA description: The image displays a graph with two different types of data, one on the left side and the other on t...
Loaded 6 paragraph data entries
Prepared 6 prompts
Image tag lists: 6
Image projection lists: 6
Initializing LLM with model: Qwen/Qwen2.5-7B-Instruct
INFO 09-01 02:06:47 [utils.py:326] non-default args: {'model': 'Qwen/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'dtype': 'float16', 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'enforce_eager': True}
INFO 09-01 02:06:54 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
WARNING 09-01 02:06:54 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-01 02:06:54 [__init__.py:1750] Using max model len 32768
INFO 09-01 02:06:54 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-01 02:06:54 [__init__.py:3565] Cudagraph is disabled under eager mode
WARNING 09-01 02:06:55 [__init__.py:2921] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-01 02:07:01 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=1112488)[0;0m INFO 09-01 02:07:03 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=1112488)[0;0m INFO 09-01 02:07:03 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]   File "/data/cl195/conda/envs/vllm312/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=1112488)[0;0m ERROR 09-01 02:07:05 [core.py:700] ValueError: Free memory on device (32.05/47.53 GiB) on startup is less than desired GPU memory utilization (0.92, 43.73 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
INFO 09-01 02:08:35 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
INFO 09-01 02:12:21 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
INFO 09-01 02:15:45 [__init__.py:241] Automatically detected platform cuda.
Loading data with VLM=False, MODEL=Qwen/Qwen2.5-7B-Instruct
Loaded LLaVA model: llava-hf/llava-1.5-7b-hf
